// Données de contenu pour chaque application
export const APPS_DATA = {
  memoire: {
    id: 'memoire',
    icon: '🏛️',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #78350f, #451a03)',
    category: 'Projet d\'État — UNESCO',
    title: 'Mémoire de la Nation',
    tagline: '54 ans d\'histoire sénégalaise, numérisés par l\'IA pour l\'éternité.',
    description: 'Le Soleil publie depuis 1970. Chaque page, chaque ligne, chaque photo raconte le Sénégal. Mémoire de la Nation est le projet de préservation le plus ambitieux d\'Afrique de l\'Ouest : rendre ce patrimoine indestructible, recherchable et accessible à tous.',
    stats: [
      { value: '2 450 000', label: 'Pages à numériser', icon: '📄' },
      { value: '99.8%', label: 'Précision OCR (Wolof/FR)', icon: '🎯' },
      { value: '54 ans', label: 'D\'histoire préservée', icon: '📅' },
    ],
    howItWorks: [
      { step: '01', title: 'Numérisation Physique', desc: 'Les volumes papier des archives sont scannés en haute résolution (600 DPI) dans le centre de numérisation du Soleil.' },
      { step: '02', title: 'Reconnaissance IA (OCR)', desc: 'Un modèle d\'IA entraîné sur le Wolof et le français extrait le texte, les entités (personnes, lieux) et les dates de chaque page.' },
      { step: '03', title: 'Indexation & Accès', desc: 'Chaque document est indexé dans une base de données souveraine, consultable en plein texte par les chercheurs, étudiants et citoyens.' },
    ],
    innovation: {
      title: 'La première IA patrimoniale africaine bilingue Wolof/Français',
      before: 'Des milliers de volumes physiques qui jaunissent dans des réserves, inaccessibles, fragiles, et condamnés à disparaître.',
      after: 'Un corpus numérique vivant, interrogeable par l\'IA, citable dans les thèses, et préservé dans des data centers redondants en sol sénégalais.',
    },
    valueFor: [
      { who: 'Chercheurs & Historiens', value: 'Accès en 3 secondes à n\'importe quel article depuis 1970. Plus besoin de se déplacer aux archives physiques.' },
      { who: 'Gouvernement & UNESCO', value: 'Un dossier de candidature au Patrimoine Mondial de l\'Information soutenu par la preuve numérique.' },
      { who: 'Journalistes', value: 'Recoupement automatique d\'informations avec les précédents historiques.' },
      { who: 'Étudiants & Lycéens', value: 'Source primaire fiable et gratuite pour les travaux de recherche et dissertations.' },
    ],
  },

  executif: {
    id: 'executif',
    icon: '💼',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #7f1d1d, #450a0a)',
    category: 'B2G — Niveau Confidentiel',
    title: 'Soleil Exécutif',
    tagline: 'L\'intelligence médiatique au service de la décision d\'État.',
    description: 'Les décideurs sénégalais méritent une information synthétisée, vérifiée et ultra-sécurisée. Soleil Exécutif est un portail B2G exclusif qui compile chaque matin, grâce à l\'IA, l\'essentiel des enjeux géopolitiques, économiques et sociaux pour les Ministres, Directeurs et la Présidence.',
    stats: [
      { value: '6h00', label: 'Heure du Briefing Quotidien', icon: '⏰' },
      { value: '500+', label: 'Sources agrégées en temps réel', icon: '🌐' },
      { value: '100%', label: 'Accès chiffré & biométrique', icon: '🔐' },
    ],
    howItWorks: [
      { step: '01', title: 'Veille Algorithmique', desc: 'L\'IA analyse en permanence 500+ sources (médias nationaux, OSINT, réseaux sociaux) pour détecter les signaux faibles.' },
      { step: '02', title: 'Synthèse & Hiérarchisation', desc: 'Les événements sont classés par niveau d\'urgence (vert/orange/rouge) et mis en forme dans un briefing concis de 5 minutes de lecture.' },
      { step: '03', title: 'Livraison Sécurisée', desc: 'Le briefing est accessible via une authentification biométrique sur une application dédiée, hébergée en souveraineté nationale.' },
    ],
    innovation: {
      title: 'L\'OSINT (Renseignement Open Source) à la portée des cabinets ministériels',
      before: 'Les conseillers compilent manuellement des dizaines de revues de presse hétérogènes. L\'information arrive tard, incomplète ou biaisée.',
      after: 'Un briefing IA personnalisé selon les portefeuilles ministériels, livré à 6h00 avec des recommandations d\'action stratégique.',
    },
    valueFor: [
      { who: 'Présidence de la République', value: 'Vision 360° de la situation nationale avant le Conseil des Ministres.' },
      { who: 'Ministères Techniques', value: 'Alertes précoces sur les crises sociales naissantes (grèves, tensions).' },
      { who: 'Ambassades & Représentations', value: 'Image-pays actualisée en temps réel pour les négociations diplomatiques.' },
      { who: 'Services de Sécurité', value: 'Détection des tendances sur les réseaux sociaux avant qu\'elles ne deviennent des crises.' },
    ],
  },

  education: {
    id: 'education',
    icon: '🎓',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #4c1d95, #2e1065)',
    category: 'EdTech — Ministère de l\'Éducation',
    title: 'Soleil Éducation',
    tagline: 'L\'actualité comme salle de classe. Le journal comme manuel scolaire.',
    description: 'Soleil Éducation transforme les articles du Soleil en leçons pédagogiques validées par le Ministère de l\'Éducation Nationale. Chaque jour, les enseignants reçoivent une sélection d\'articles adaptés à leur niveau, accompagnés d\'exercices de compréhension générés par l\'IA.',
    stats: [
      { value: '3 200', label: 'Établissements scolaires ciblés', icon: '🏫' },
      { value: '850K', label: 'Élèves potentiels touchés', icon: '👨‍🎓' },
      { value: '12', label: 'Matières couvertes (Hist/Géo/Français...)', icon: '📚' },
    ],
    howItWorks: [
      { step: '01', title: 'Sélection Pédagogique IA', desc: 'Chaque matin, l\'IA sélectionne les articles les plus pertinents par matière et niveau scolaire (6ème à Terminale).' },
      { step: '02', title: 'Adaptation du Contenu', desc: 'Les articles sont simplifiés, annotés et enrichis de questions de compréhension et de quiz adaptés au curriculum national.' },
      { step: '03', title: 'Déploiement en Classe', desc: 'L\'enseignant accède à son espace dédié, projette l\'article en classe et lance le quiz interactif depuis son téléphone.' },
    ],
    innovation: {
      title: 'L\'actualité réelle comme support pédagogique vivant — une première en Afrique subsaharienne',
      before: 'Des manuels scolaires datant de 5 à 10 ans, déconnectés de la réalité contemporaine du Sénégal.',
      after: 'Des leçons basées sur des événements réels de la semaine, rendant la compréhension plus intuitive et mémorisable pour les élèves.',
    },
    valueFor: [
      { who: 'Enseignants', value: 'Des ressources pédagogiques fraîches prêtes à l\'emploi, sans travail de préparation supplémentaire.' },
      { who: 'Élèves', value: 'Apprendre à lire et analyser l\'information officielle, compétence clé du citoyen moderne.' },
      { who: 'Ministère de l\'Éducation', value: 'Un levier pour améliorer les scores de compréhension de lecture au BFEM et au BAC.' },
      { who: 'Le Soleil (Éditeur)', value: 'Contrat de partenariat pluriannuel avec l\'État, garantissant un financement stable.' },
    ],
  },

  zerodata: {
    id: 'zerodata',
    icon: '📶',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #064e3b, #022c22)',
    category: 'Inclusion Numérique — Partenariat Telecom',
    title: 'Zéro Data',
    tagline: 'L\'information nationale, gratuite pour tous. Sans forfait, sans barrière.',
    description: 'Au Sénégal, des millions de citoyens en zone rurale ont un téléphone mais pas les moyens de payer un forfait data. Zéro Data est un accord de Zero-Rating avec Sonatel et Free : naviguer sur l\'application Le Soleil ne coûte aucun méga-octet. L\'information redevient un droit universel.',
    stats: [
      { value: '5M+', label: 'Citoyens ciblés (zones rurales)', icon: '🌍' },
      { value: '0 MO', label: 'Consommé pour lire Le Soleil', icon: '📡' },
      { value: '3', label: 'Opérateurs partenaires (Sonatel, Free, Expresso)', icon: '🤝' },
    ],
    howItWorks: [
      { step: '01', title: 'Accord Commercial Signé', desc: 'Le Soleil signe un accord de Zero-Rating avec les opérateurs. Ces derniers sont compensés par la publicité générée par la masse d\'audience.' },
      { step: '02', title: 'Whitelisting Réseau', desc: 'Les domaines du Soleil sont inscrits sur la liste blanche des opérateurs. Tout trafic vers ces domaines n\'est pas déduit du forfait de l\'abonné.' },
      { step: '03', title: 'Application PWA Ultra-Légère', desc: 'L\'application pèse moins de 2 Mo, fonctionne hors-ligne (cache intelligent) et est optimisée pour les réseaux 2G des zones enclavées.' },
    ],
    innovation: {
      title: 'Le modèle Facebook Free Basics, appliqué à la presse nationale souveraine',
      before: 'L\'information de qualité est réservée aux citoyens urbains qui peuvent payer un forfait data. Les ruraux dépendent de la radio ou de la rumeur.',
      after: 'Le Sénégal entier lit le même journal national. L\'unité d\'information reconstruit le tissu civique national et réduit la fracture numérique.',
    },
    valueFor: [
      { who: 'Citoyens Ruraux', value: 'Accès à l\'actualité nationale officielle sans aucun coût. Fin de la désertification informationnelle.' },
      { who: 'Annonceurs Publicitaires', value: 'Accès à une audience de masse (5M+) impossible à atteindre autrement. CPM ultra-compétitif.' },
      { who: 'Opérateurs Télécom', value: 'Image RSE positive. Différenciation sur le marché par l\'accès à un contenu national premium gratuit.' },
      { who: 'Gouvernement', value: 'Outil de communication institutionnelle atteignant même les villages les plus isolés.' },
    ],
  },

  jeux: {
    id: 'jeux',
    icon: '🎮',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #064e3b, #065f46)',
    category: 'Gamification — Rétention Audience',
    title: 'Soleil Jeux',
    tagline: 'L\'habitude quotidienne que 1 million de Sénégalais attendent chaque matin.',
    description: 'Le Wordle a conquis le New York Times en 2022 et lui a valu des millions d\'utilisateurs quotidiens. Soleil Jeux applique cette formule au Sénégal : un mot mystère en Wolof, un quiz sur l\'actualité du jour. Simple. Addictif. Et profondément ancré dans la culture locale.',
    stats: [
      { value: '89%', label: 'Taux de rétention à J+7 (benchmark Wordle)', icon: '🔄' },
      { value: '4 min', label: 'Temps moyen passé par session de jeu', icon: '⏱️' },
      { value: '1er', label: 'Wordle en langue Wolof au monde', icon: '🌍' },
    ],
    howItWorks: [
      { step: '01', title: 'Le Mot du Jour (Wolof)', desc: 'Chaque matin à minuit, un nouveau mot en Wolof est sélectionné. L\'utilisateur a 6 tentatives pour le deviner, avec des indices couleur (présent/absent/correct).' },
      { step: '02', title: 'Le Quiz Actualité', desc: '5 questions basées sur les articles publiés par Le Soleil dans les dernières 24h. Testeri ses connaissances tout en s\'informant.' },
      { step: '03', title: 'Partage Viral', desc: 'Le résultat se partage en 1 clic sur WhatsApp avec un tableau graphique, créant un effet de propagation organique et gratuit.' },
    ],
    innovation: {
      title: 'La gamification de la langue Wolof — valoriser la culture locale pour fidéliser une audience jeune',
      before: 'Les médias sénégalais ne proposent aucun contenu interactif. Les jeunes se tournent vers TikTok et des contenus étrangers pour leur divertissement.',
      after: 'Un rendez-vous culturel et linguistique quotidien qui fidélise les 18-35 ans et crée une communauté autour du média Le Soleil.',
    },
    valueFor: [
      { who: 'Jeunes (18-35 ans)', value: 'Un jeu gratuit et culturellement ancré, jouable en 3 minutes pendant le trajet du matin.' },
      { who: 'Diaspora Sénégalaise', value: 'Un moyen de garder le lien avec la langue et la culture locale depuis l\'étranger.' },
      { who: 'Annonceurs', value: 'Un placement publicitaire dans un environnement ultra-engagé (l\'utilisateur est concentré, actif, et de bonne humeur).' },
      { who: 'Le Soleil', value: 'Un flux quotidien garanti d\'utilisateurs qui, après le jeu, lisent les articles associés.' },
    ],
  },

  briefing: {
    id: 'briefing',
    icon: '📧',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #78350f, #92400e)',
    category: 'Newsletters — Relation Directe',
    title: 'Soleil Briefing',
    tagline: 'L\'expertise du Soleil, distillée dans votre boîte mail. Sans algorithme.',
    description: 'Les algorithmes de Facebook et Google décident ce que vous lisez. Soleil Briefing court-circuite ces intermédiaires : une newsletter thématique, envoyée directement aux abonnés, sans dépendre d\'aucune plateforme externe. Un lien direct et pérenne entre le lecteur et le journaliste.',
    stats: [
      { value: '45%', label: 'Taux d\'ouverture moyen (vs 22% secteur)', icon: '📬' },
      { value: '12 450', label: 'Abonnés cibles à 6 mois (L\'Édition Éco)', icon: '👥' },
      { value: '0', label: 'Dépendance aux algorithmes sociaux', icon: '🔓' },
    ],
    howItWorks: [
      { step: '01', title: 'Choix du Thème', desc: 'L\'abonné choisit ses centres d\'intérêt : Économie, Politique, Sport, Diaspora, Technologie. Il reçoit uniquement ce qui lui correspond.' },
      { step: '02', title: 'Curation IA + Journaliste', desc: 'L\'IA présélectionne les 5 articles les plus importants du jour. Le journaliste thématique valide, complète et ajoute son analyse exclusive.' },
      { step: '03', title: 'Livraison Personnalisée', desc: 'La newsletter arrive à l\'heure choisie par l\'abonné (6h00 ou 12h00), dans un format lisible en 3 minutes, sur mobile ou desktop.' },
    ],
    innovation: {
      title: 'La newsletter comme antidote aux fausses informations — livrer la vérité directement, sans détour',
      before: 'L\'abonné reçoit des informations via des groupes WhatsApp non vérifiés ou des flux Facebook dont l\'algorithme priorise le sensationnel.',
      after: 'Une source fiable, signée, avec le nom du journaliste, livré directement. Le lecteur sait exactement d\'où vient l\'information.',
    },
    valueFor: [
      { who: 'Décideurs & Cadres', value: 'L\'essentiel de l\'économie sénégalaise en 3 minutes chaque matin, avant leur réunion de direction.' },
      { who: 'Diaspora', value: 'Un lien informatif hebdomadaire avec le pays, sans avoir à chercher activement l\'information.' },
      { who: 'Annonceurs Premium', value: 'Un ciblage parfait. Placer une pub dans "L\'Édition Éco" garantit de toucher uniquement les décideurs économiques.' },
      { who: 'Le Soleil', value: 'Une base d\'abonnés email directement détenue, sans dépendance aux plateformes tierces.' },
    ],
  },

  audio: {
    id: 'audio',
    icon: '🎧',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #4c1d95, #3b0764)',
    category: 'Audio — Accessibilité & Mobilité',
    title: 'Soleil Audio',
    tagline: 'Écoutez l\'actualité. Même les mains occupées. Même sans lire.',
    description: 'Au Sénégal, la tradition orale est reine. Soleil Audio est la réponse numérique à cette réalité culturelle. Tous les articles sont disponibles en audio via une technologie Text-to-Speech en Wolof et en français. Les podcasts de débats exclusifs offrent une analyse plus profonde des enjeux nationaux.',
    stats: [
      { value: '100%', label: 'Des articles lisibles en audio', icon: '🎙️' },
      { value: '2', label: 'Langues (Français & Wolof natif)', icon: '🗣️' },
      { value: '30 min', label: 'Durée moy. écoute/session (vs 4 min lecture)', icon: '⏱️' },
    ],
    howItWorks: [
      { step: '01', title: 'Conversion Text-to-Speech IA', desc: 'Chaque article publié est automatiquement converti en audio par notre moteur IA entraîné sur la phonétique wolof et française.' },
      { step: '02', title: 'Podcasts de Débat', desc: 'Des journalistes et experts sénégalais enregistrent des débats exclusifs (30-45 min) analysant l\'actualité en profondeur.' },
      { step: '03', title: 'Transcription Synchronisée', desc: 'En mode Karaoke, le texte défile en surbrillance au rythme de la voix, aidant les apprenants à associer son et texte.' },
    ],
    innovation: {
      title: 'Le premier Text-to-Speech en Wolof au monde — rendre la presse accessible aux 40% de Sénégalais non-francophones',
      before: 'Des millions de Sénégalais maîtrisant le Wolof mais pas le français écrit sont exclus de la presse nationale.',
      after: 'Chaque article est accessible à voix haute en Wolof. La presse nationale touche enfin l\'intégralité du peuple qu\'elle est censée représenter.',
    },
    valueFor: [
      { who: 'Populations Non-Francophones', value: 'Accès à l\'information nationale officielle dans leur langue maternelle, sans barrière de la lecture.' },
      { who: 'Actifs en Déplacement', value: 'S\'informer pendant les transports en commun ou lors de travaux ménagers — sans regarder un écran.' },
      { who: 'Malvoyants', value: 'Un accès équitable à l\'information, conformément aux engagements d\'accessibilité universelle.' },
      { who: 'Annonceurs Audio', value: 'Un marché publicitaire audio sénégalais inexistant à ce jour — une opportunité de premier entrant.' },
    ],
  },

  pro: {
    id: 'pro',
    icon: '📈',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #1e3a5f, #1e3a8a)',
    category: 'B2B — Intelligence Économique',
    title: 'Soleil Pro',
    tagline: 'La data économique sénégalaise la plus fiable du marché. Abonnement entreprise.',
    description: 'Les décideurs du secteur privé, les investisseurs étrangers et les institutions financières ont besoin de données vérifiées sur l\'économie sénégalaise. Soleil Pro agrège les marchés publics, les annonces légales, et les analyses sectorielles publiées par Le Soleil en 54 ans dans une plateforme de data intelligence B2B.',
    stats: [
      { value: '50 000', label: 'CFA/mois — Abonnement de base', icon: '💰' },
      { value: '2 500+', label: 'Entreprises cibles au Sénégal', icon: '🏢' },
      { value: '84', label: 'Appels d\'offres actifs (mise à jour quotidienne)', icon: '📋' },
    ],
    howItWorks: [
      { step: '01', title: 'Agrégation des Données Publiques', desc: 'L\'IA collecte et structure toutes les données économiques publiées au Journal Officiel, aux DCMP et dans les pages économiques du Soleil.' },
      { step: '02', title: 'Analyse Sectorielle', desc: 'Des rapports sectoriels (BTP, Énergie, Agro-industrie) sont produits chaque trimestre par les journalistes économiques du Soleil et enrichis par des algorithmes prédictifs.' },
      { step: '03', title: 'Dashboard en Temps Réel', desc: 'Chaque abonné dispose d\'un tableau de bord personnalisé selon son secteur, avec des alertes sur les nouvelles opportunités d\'affaires.' },
    ],
    innovation: {
      title: 'L\'archive du Soleil comme actif data B2B — 54 ans de données économiques exploitables par l\'IA',
      before: 'Les investisseurs étrangers commandent des rapports à des cabinets de conseil internationaux (McKinsey, PWC) à des tarifs prohibitifs, avec des délais de 6 semaines.',
      after: 'Un abonnement mensuel à 50 000 CFA donne accès à des rapports plus précis, car fondés sur les données locales primaires, en temps réel.',
    },
    valueFor: [
      { who: 'PME Sénégalaises', value: 'Identifier les appels d\'offres correspondant à leur activité avant leurs concurrents. Un avantage concurrentiel décisif.' },
      { who: 'Investisseurs Étrangers', value: 'Due diligence fiable sur le marché sénégalais à un coût minimal, en français ou en anglais.' },
      { who: 'Banques & Assurances', value: 'Données de marché actualisées pour la notation de risque des dossiers de crédit sectoriels.' },
      { who: 'Cabinets d\'Avocats', value: 'Accès instantané aux annonces légales, publications judiciaires et modifications statutaires.' },
    ],
  },

  events: {
    id: 'events',
    icon: '🎟️',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #831843, #500724)',
    category: 'Événementiel — Extension de Marque',
    title: 'Le Soleil Events',
    tagline: 'Quand le Sénégal se réunit pour débattre, Le Soleil organise la rencontre.',
    description: 'Le Soleil est la marque médiatique la plus légitime du Sénégal. Soleil Events capitalise sur cette autorité pour organiser des forums, masterclasses et débats qui rassemblent les décideurs, experts et citoyens autour des enjeux nationaux. Un prolongement physique premium de la marque.',
    stats: [
      { value: '1 500+', label: 'Participants au Forum Annuel', icon: '👥' },
      { value: '12', label: 'Événements organisés par an', icon: '📅' },
      { value: '80M CFA', label: 'Revenus événementiels projetés (an 1)', icon: '💰' },
    ],
    howItWorks: [
      { step: '01', title: 'Identification des Enjeux', desc: 'La rédaction identifie les thèmes qui dominent l\'actualité et pour lesquels les lecteurs veulent des réponses (emploi, pétrole, éducation).' },
      { step: '02', title: 'Curation des Intervenants', desc: 'Le Soleil invite les meilleurs experts, ministres et entrepreneurs à débattre. La légitimité du journal garantit la participation des personnalités de premier plan.' },
      { step: '03', title: 'Distribution & Monétisation', desc: 'Les conférences sont retransmises en live sur Soleil TV+, enregistrées en podcast et les billets sont vendus via l\'application (avec e-ticket QR Code).' },
    ],
    innovation: {
      title: 'Transformer le contenu éditorial en événement physique — la conférence comme produit média',
      before: 'Les revenus du Soleil proviennent uniquement de la publicité et des abonnements papier. Deux sources qui s\'érodent chaque année.',
      after: 'Une troisième source de revenus récurrente et à forte marge : les événements. Chaque forum génère du contenu éditorial pour 6 mois d\'articles de suivi.',
    },
    valueFor: [
      { who: 'Entreprises Sponsors', value: 'Association de la marque à un événement de prestige national. Visibilité auprès de 1500 décideurs en un seul lieu.' },
      { who: 'Intervenants (Experts, Ministres)', value: 'Une tribune nationale légitime et une audience garantie grâce à l\'audience préexistante du Soleil.' },
      { who: 'Participants', value: 'Networking de haut niveau et accès aux insights des experts les plus influents du Sénégal.' },
      { who: 'Diaspora (En Ligne)', value: 'Participation à distance via le live-stream sur Soleil TV+. Les Sénégalais de l\'étranger restent connectés aux débats du pays.' },
    ],
  },

  ia: {
    id: 'ia',
    icon: '🤖',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #083344, #0c4a6e)',
    category: 'Intelligence Artificielle — Innovation Core',
    title: 'Soleil IA',
    tagline: '54 ans d\'archives interrogées en langage naturel. Le Google du Sénégal.',
    description: 'Imaginez pouvoir demander à quelqu\'un qui a lu tous les journaux du Sénégal depuis 1970 : n\'importe quelle question sur l\'histoire, l\'économie ou la politique du pays. C\'est Soleil IA. Un assistant conversationnel branché exclusivement sur les archives vérifiées du Soleil — garantissant des réponses sourcées, jamais hallucinées.',
    stats: [
      { value: '54 ans', label: 'D\'archives exploitables par l\'IA', icon: '🗄️' },
      { value: '100%', label: 'Des réponses citent leur source (article + date)', icon: '✅' },
      { value: '<2s', label: 'Temps de réponse moyen', icon: '⚡' },
    ],
    howItWorks: [
      { step: '01', title: 'Base de Connaissance Souveraine', desc: 'Toutes les archives numérisées du Soleil sont converties en vecteurs (embeddings) et stockées dans une base de données vectorielle souveraine.' },
      { step: '02', title: 'RAG (Retrieval-Augmented Generation)', desc: 'À chaque question, l\'IA recherche les extraits d\'articles les plus pertinents, puis génère une réponse basée uniquement sur ces sources vérifiées.' },
      { step: '03', title: 'Citation Systématique', desc: 'Chaque réponse est accompagnée de la référence exacte (Numéro d\'édition, Date, Titre de l\'article) pour permettre la vérification.' },
    ],
    innovation: {
      title: 'L\'IA anti-hallucination — la seule IA qui ne peut répondre que sur des faits sénégalais vérifiés par des journalistes',
      before: 'ChatGPT répond sur le Sénégal avec des informations souvent inexactes, datées, voire inventées. Aucune source, aucune accountability.',
      after: 'Soleil IA ne répond que ce qu\'elle a lu dans Le Soleil. Si elle ne sait pas, elle dit "Je n\'ai pas d\'information sur ce sujet dans nos archives". Zéro hallucination.',
    },
    valueFor: [
      { who: 'Journalistes', value: 'Recouper une information en 2 secondes avec les précédents historiques. Jamais de doublons, jamais de fausse primeur.' },
      { who: 'Chercheurs & Universitaires', value: 'Corpus de recherche primaire sénégalais unique au monde, interrogeable en langage naturel.' },
      { who: 'Avocats & Juristes', value: 'Retrouver la couverture médiatique d\'une affaire judiciaire ou d\'une loi promulguée en quelques secondes.' },
      { who: 'Citoyens Curieux', value: 'Comprendre l\'histoire de son pays, en posant des questions simples, et en recevant des réponses sourcées et vérifiées.' },
    ],
  },
};
